import 'package:flutter/material.dart';
import 'package:flutter_application_1/controllers/users/saveOrderController.dart';
import 'package:flutter_application_1/models/cartitem.dart';
import 'package:flutter_application_1/models/chitiet_donhang.dart';
import 'package:flutter_application_1/models/dathang.dart';
import 'package:flutter_application_1/services/api_connection.dart';
import 'package:flutter_application_1/services/cart.dart';
import 'package:flutter_application_1/services/userInfoRemember.dart';
import 'package:flutter_application_1/views/users/success_order.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:get/get.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class CheckoutScreen extends StatefulWidget {
  final List<CartItem> cartItems; // Pass cart items from the previous screen
  const CheckoutScreen({Key? key, required this.cartItems}) : super(key: key);

  @override
  _CheckoutScreenState createState() => _CheckoutScreenState();
}

class _CheckoutScreenState extends State<CheckoutScreen> {
  late CurrentUSer _currentUser;
  final TextEditingController _addressController = TextEditingController();
  final TextEditingController _phoneController = TextEditingController();
  final TextEditingController _nameController = TextEditingController();
  final Saveordercontroller _addProduct = Get.put(Saveordercontroller());

  @override
  void initState() {
    super.initState();
    _currentUser = Get.put(CurrentUSer());  // Initialize user info
    _nameController.text = _currentUser.user.user_name;  // Set default name
  }

  int getTotalPrice() {
    int total = 0;
    for (var item in widget.cartItems) {
      total += item.giasp * item.soluong;
    }
    return total;
  }

  // Send data to the server to save the order
Future<void> checkout() async {
  final String name = _nameController.text;
  final String phone = _phoneController.text;
  final String address = _addressController.text;

  if (name.isEmpty || address.isEmpty || phone.isEmpty) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text('Vui lòng nhập đầy đủ các trường.')),
    );
    return;
  }

  // Prepare the order data
  Dathang order = Dathang(
    id_dathang: 1,
    madathang: 'MDH${DateTime.now().millisecondsSinceEpoch}', // Unique order ID (could be more sophisticated)
    makh: 'MKH${_currentUser.user.user_id}',
    trangthai: 'Chờ xác nhận',
    tongtien: getTotalPrice(),
    ngaydathang: DateTime.now(),
    giaohang: 'COD',
    id_kh: _currentUser.user.user_id,
    tenkh: name,
    sdt: phone,
    diachi: address
  );

  // Prepare the order details (chitiet_donhang) from the cart items
  List<ChitietDonhang> orderDetails = widget.cartItems.map((item) {
    return ChitietDonhang(
      id_ctdonhang: 0,  // ID will be auto-generated by the database
      madathang: order.madathang,
      makh: order.makh,
      id_sanpham: int.parse(item.id_sanpham),
      tensp: item.tensp,
      soluong: item.soluong,
      giamgia: 0,  // Assuming no discount
      giatien: item.giasp,
      tongtien: item.giasp * item.soluong,
      trangthai: 'Chờ xác nhận',
      ngaydat: DateTime.now(),
      id_dathang: order.id_dathang,
      id_kh: order.id_kh,
    );
  }).toList();

  // Convert both order and orderDetails to JSON and send it to the server
  Map<String, dynamic> data = {
    'madathang': order.madathang,
    'makh': order.makh,
    'trangthai': order.trangthai,
    'tongtien': order.tongtien,
    'ngaydathang': order.ngaydathang.toIso8601String(),
    'giaohang': order.giaohang,
    'id_kh': order.id_kh,
    'tenkh': order.tenkh,
    'sdt': order.sdt,
    'diachi': order.diachi,
    'chitiet': orderDetails.map((item) => item.toJson()).toList(), // Order details
  };

  var response = await http.post(
    Uri.parse(API.saveOrder),
    headers: {"Content-Type": "application/json"},
    body: jsonEncode(data),
  );

  if (response.statusCode == 200) {
    var resBody = jsonDecode(response.body);
    if (resBody['successAddOrder'] == true) {
      Fluttertoast.showToast(msg: 'Đặt hàng thành công');
      SharedPreferencesCart.clearCart();

      Navigator.pushReplacement(
        context,
        MaterialPageRoute(builder: (context) => SuccessOrderScreen()),
      );

    } else {
      Fluttertoast.showToast(msg: 'Đặt hàng thất bại');
    }
  } else {
    Fluttertoast.showToast(msg: 'Failed to connect to the server');
  }
}


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Checkout'),
        backgroundColor: Colors.blue.shade400,
        foregroundColor: Colors.white,
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Order Summary',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              ListView.builder(
                shrinkWrap: true,
                itemCount: widget.cartItems.length,
                itemBuilder: (context, index) {
                  final item = widget.cartItems[index];
                  return ListTile(
                    leading: Image.asset(item.anhsp, width: 50, height: 50),
                    title: Text(item.tensp),
                    subtitle: Text('Quantity: ${item.soluong}'),
                    trailing: Text('Total: ${item.giasp * item.soluong} VND'),
                  );
                },
              ),
              Divider(),
              Text('User Information', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              TextField(
                controller: _nameController,
                decoration: InputDecoration(labelText: 'Full Name'),
              ),
              TextField(
                controller: _phoneController,
                decoration: InputDecoration(labelText: 'Phone Number'),
              ),
              TextField(
                controller: _addressController,
                decoration: InputDecoration(labelText: 'Shipping Address'),
                maxLines: 3,
              ),
              Divider(),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Total Amount:',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                  ),
                  Text(
                    '${getTotalPrice()} VND',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
              SizedBox(height: 20),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  ElevatedButton(
                    onPressed: checkout,
                    child: Padding(
                      padding: EdgeInsets.symmetric(vertical: 0, horizontal: 25),
                      child: Text(
                        'Đặt hàng',
                        style: TextStyle(color: Colors.white),
                      ),
                    ),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.blue.shade400,
                      padding: EdgeInsets.symmetric(vertical: 14),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
